name: Publish website
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v4
            - name: Setup hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: "latest"
                  extended: true
            - name: Clone submodules
              run: git submodule init && git submodule update
            - name: Build
              run: hugo --minify && mv public/index.xml public/rss.xml
            - name: Add CNAME record
              run: echo "severkar.eu" > public/CNAME
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
